## TASK1

In [2]:
#Question 1
'''
Write a function to compute 5/0 and use try/except to catch the exceptions.
'''

try:
    print(5/0)
except Exception as e:
    print("Error Code:",str(e))

Error Code: division by zero


In [3]:
#Question 2
'''
Implement a Python program to generate all sentences where subject is in ["Americans","Indians"] and verb is in 
["Play", "watch"] and the object is in ["Baseball","cricket"].Hint: Subject,Verb and Object should be declared in the program 
as shown below.subjects=["Americans ","Indians"]verbs=["play","watch"]objects=["Baseball","Cricket"]
'''
subject = ["Americans","Indians"]
verb = ["play","watch"]
game = ["Baseball","Cricket"]

for i in subject:
    for j in verb:
        for k in game:
            print(i+' '+j+' '+k+'.')

Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


In [12]:
new_list = [i+' '+j+' '+k+'.' for i in subject for j in verb for k in game]
print('\n'.join(new_list))

Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


## Task 2

In [8]:
'''
Write a function so that the columns of the output matrix are powers of the input vector.The order of the powers is determined bythe
increasing boolean argument.Specifically, when increasing is False,the i-th output column is the input vector raised element-wise
to the powerof N - i - 1.HINT:Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.
'''
import numpy as np

def vander_matrix(input_vector,column_size):
    matrix = np.array([x**i for x in input_vector for i in range(column_size)]).reshape(len(input_vector),column_size)
    return matrix

input_vector = [1,2,3,4,5]
columns = 3
output = vander_matrix(input_vector, columns)
print(output)

    


[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]
